<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlantsSpeciesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('plants_species')->insert([
            [
                'plant_species_id' => 1,
                'plant_species_name' => 'Achillea',
                'plant_family_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 2,
                'plant_species_name' => 'Achillea',
                'plant_family_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 3,
                'plant_species_name' => 'Adoxa',
                'plant_family_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 4,
                'plant_species_name' => 'Vaccinium',
                'plant_family_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 5,
                'plant_species_name' => 'Alchemilla',
                'plant_family_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 6,
                'plant_species_name' => 'Sorbus',
                'plant_family_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 7,
                'plant_species_name' => 'Alliaria',
                'plant_family_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 8,
                'plant_species_name' => 'Angelica',
                'plant_family_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 9,
                'plant_species_name' => 'Galium',
                'plant_family_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 10,
                'plant_species_name' => 'Crataegus',
                'plant_family_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 11,
                'plant_species_name' => 'Geum',
                'plant_family_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 12,
                'plant_species_name' => 'Campanula',
                'plant_family_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 13,
                'plant_species_name' => 'Carduus',
                'plant_family_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 14,
                'plant_species_name' => 'Epilobium',
                'plant_family_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 15,
                'plant_species_name' => 'Gentiana',
                'plant_family_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 16,
                'plant_species_name' => 'Geranium',
                'plant_family_id' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 17,
                'plant_species_name' => 'Lilium',
                'plant_family_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 18,
                'plant_species_name' => 'Larix',
                'plant_family_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 19,
                'plant_species_name' => 'Dactylorhiza',
                'plant_family_id' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 20,
                'plant_species_name' => 'Antennaria',
                'plant_family_id' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 21,
                'plant_species_name' => 'Rhododendron',
                'plant_family_id' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 22,
                'plant_species_name' => 'Saxifraga',
                'plant_family_id' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 23,
                'plant_species_name' => 'Thymus',
                'plant_family_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 24,
                'plant_species_name' => 'Veronica',
                'plant_family_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 25,
                'plant_species_name' => 'Phalaris',
                'plant_family_id' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 26,
                'plant_species_name' => 'Impatiens',
                'plant_family_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 27,
                'plant_species_name' => 'Impatiens',
                'plant_family_id' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 28,
                'plant_species_name' => 'Impatiens',
                'plant_family_id' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 29,
                'plant_species_name' => 'Bazzania',
                'plant_family_id' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 30,
                'plant_species_name' => 'Buxus',
                'plant_family_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 31,
                'plant_species_name' => 'Callitriche',
                'plant_family_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 32,
                'plant_species_name' => 'Callitriche',
                'plant_family_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 33,
                'plant_species_name' => 'Calluna',
                'plant_family_id' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 34,
                'plant_species_name' => 'Campanula',
                'plant_family_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 35,
                'plant_species_name' => 'Deschampsia',
                'plant_family_id' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 36,
                'plant_species_name' => 'Avenella',
                'plant_family_id' => 36,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 37,
                'plant_species_name' => 'Asplenium',
                'plant_family_id' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 38,
                'plant_species_name' => 'Cardamine',
                'plant_family_id' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 39,
                'plant_species_name' => 'Cardamine',
                'plant_family_id' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 40,
                'plant_species_name' => 'Centaurea',
                'plant_family_id' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 41,
                'plant_species_name' => 'Carpinus',
                'plant_family_id' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_species_id' => 42,
                'plant_species_name' => 'Castanea',
                'plant_family_id' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}