<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlantsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('plants')->insert([
            [
                'plant_id' => 1,
                'plant_common_name' => 'Achillée millefeuille',
                'plant_scientific_name' => 'Achillea millefolium',
                'plant_description' => "L'Achillée millefeuille est une plante herbacée vivace, connue pour ses propriétés médicinales. Ses feuilles finement découpées ressemblent à des plumes, et ses petites fleurs blanches ou roses sont regroupées en ombelles plates. Elle est couramment utilisée pour ses effets anti-inflammatoires et cicatrisants.",
                'plant_image_src' => 'achillee_millefeuille',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 2,
                'plant_common_name' => 'Achillée sternutatoire',
                'plant_scientific_name' => 'Achillea ptarmica',
                'plant_description' => "Cette plante vivace pousse dans les prairies humides. Elle est reconnaissable par ses fleurs blanches en forme de petites étoiles, portées par des tiges droites et élancées. Ses feuilles sont simples, allongées et légèrement dentées.",
                'plant_image_src' => 'achillee_sternutatoire',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 3,
                'plant_common_name' => 'Adoxe musquée',
                'plant_scientific_name' => 'Adoxa moschatellina',
                'plant_description' => "L'Adoxe musquée est une petite plante vivace des bois frais, au parfum musqué subtil. Elle se distingue par ses petites fleurs verdâtres qui forment des inflorescences sphériques et ses feuilles finement découpées à l'aspect délicat.",
                'plant_image_src' => 'adoxe_musquee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 4,
                'plant_common_name' => 'Airelle myrtille',
                'plant_scientific_name' => 'Vaccinium myrtillas',
                'plant_description' => "L'airelle myrtille est un petit arbrisseau à tiges anguleuses et à feuilles ovales, légèrement dentées. Elle produit des baies sphériques bleu foncé ou noires, très prisées pour leurs propriétés antioxydantes.",
                'plant_image_src' => 'airelle_myrtille',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 5,
                'plant_common_name' => 'Alchemille vert-jaunâtre',
                'plant_scientific_name' => 'Alchemilla xanthochlora',
                'plant_description' => "L'Alchemille est une plante vivace appréciée pour ses grandes feuilles en forme d'éventail, dont la surface est souvent couverte de gouttelettes d'eau. Ses petites fleurs jaunes-vertes forment des grappes discrètes.",
                'plant_image_src' => 'alchemille_vert_jaunatre',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 6,
                'plant_common_name' => 'Alisier blanc',
                'plant_scientific_name' => 'Sarbus aria',
                'plant_description' => "L'Alisier blanc est un arbre de taille moyenne, avec des feuilles ovales à bord denté, argentées en dessous. En automne, il produit des baies rouges qui contrastent avec son feuillage vert foncé.",
                'plant_image_src' => 'alisier_blanc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 7,
                'plant_common_name' => 'Alliaire officinale',
                'plant_scientific_name' => 'Allium petiolata',
                'plant_description' => "L'Alliaire officinale est une plante herbacée aux feuilles en forme de cœur, dentelées et légèrement brillantes. Ses petites fleurs blanches à quatre pétales apparaissent au printemps, et ses graines sont contenues dans de longues siliques.",
                'plant_image_src' => 'alliaire_officinale',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 8,
                'plant_common_name' => 'Angélique des bois',
                'plant_scientific_name' => 'Angelica sylvestris',
                'plant_description' => "Plante haute et robuste, l'Angélique des bois possède de larges feuilles composées et des ombelles de petites fleurs blanches ou roses. Elle pousse souvent en bordure des forêts.",
                'plant_image_src' => 'angelique_des_bois',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 9,
                'plant_common_name' => 'Aspérule odorante',
                'plant_scientific_name' => 'Galium odoratum',
                'plant_description' => "Petite plante tapissante des sous-bois, l'Aspérule odorante est connue pour son parfum agréable. Ses feuilles vert foncé sont disposées en verticilles autour de tiges fines, et ses petites fleurs blanches dégagent une douce fragrance.",
                'plant_image_src' => 'asperule_odorante',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 10,
                'plant_common_name' => 'Aubépine monogyne',
                'plant_scientific_name' => 'Crataegus monogyna',
                'plant_description' => "L'Aubépine monogyne est un arbuste épineux, au feuillage lobé et à fleurs blanches odorantes. Ses baies rouges, appelées cenelles, apparaissent à la fin de l'été.",
                'plant_image_src' => 'aubepine_monogyne',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 11,
                'plant_common_name' => 'Benoîte des montagnes',
                'plant_scientific_name' => 'Geum montanum',
                'plant_description' => 'Plante vivace aux fleurs jaunes solitaires, avec des feuilles pennées. Elle est adaptée aux sols pauvres des prairies alpines.',
                'plant_image_src' => 'benoite_des_montagnes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 12,
                'plant_common_name' => 'Campanule à feuilles rondes',
                'plant_scientific_name' => 'Campanula rotundifolia',
                'plant_description' => 'Délicate plante aux clochettes bleues-violettes, avec des feuilles basales arrondies et des feuilles caulinaires linéaires.',
                'plant_image_src' => 'campanule_a_feuilles_rondes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 13,
                'plant_common_name' => 'Chardon des Alpes',
                'plant_scientific_name' => 'Carduus defloratus',
                'plant_description' => 'Chardon aux capitules pourpres solitaires, avec des feuilles épineuses vert foncé. Adapté aux terrains rocailleux.',
                'plant_image_src' => 'chardon_des_alpes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 14,
                'plant_common_name' => 'Épilobe en épi',
                'plant_scientific_name' => 'Epilobium angustifolium',
                'plant_description' => 'Grande plante aux longues grappes de fleurs roses-pourpres. Commune dans les clairières et zones déboisées.',
                'plant_image_src' => 'epilobe_en_epi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 15,
                'plant_common_name' => 'Gentiane jaune',
                'plant_scientific_name' => 'Gentiana lutea',
                'plant_description' => 'Grande plante aux fleurs jaunes en verticilles. Sa racine est utilisée pour produire des boissons amères traditionnelles.',
                'plant_image_src' => 'gentiane_jaune',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 16,
                'plant_common_name' => 'Géranium des bois',
                'plant_scientific_name' => 'Geranium sylvaticum',
                'plant_description' => 'Plante vivace aux fleurs violettes-bleues, avec des feuilles profondément découpées. Commune dans les prairies montagnardes.',
                'plant_image_src' => 'geranium_des_bois',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 17,
                'plant_common_name' => 'Lys martagon',
                'plant_scientific_name' => 'Lilium martagon',
                'plant_description' => 'Magnifique lys aux fleurs roses tachetées de pourpre, aux pétales recourbés. Protégé dans certaines régions.',
                'plant_image_src' => 'lys_martagon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 18,
                'plant_common_name' => 'Mélèze d\'Europe',
                'plant_scientific_name' => 'Larix decidua',
                'plant_description' => 'Conifère qui perd ses aiguilles en hiver. Ses aiguilles vert tendre deviennent dorées en automne.',
                'plant_image_src' => 'meleze_europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 19,
                'plant_common_name' => 'Orchis tacheté',
                'plant_scientific_name' => 'Dactylorhiza maculata',
                'plant_description' => 'Orchidée aux fleurs roses-lilas marquées de points pourpres. Ses feuilles sont souvent tachetées de brun.',
                'plant_image_src' => 'orchis_tachete',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 20,
                'plant_common_name' => 'Pied de chat',
                'plant_scientific_name' => 'Antennaria dioica',
                'plant_description' => 'Petite plante tapissante aux capitules blancs ou roses, avec des feuilles argentées en rosette.',
                'plant_image_src' => 'pied_de_chat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 21,
                'plant_common_name' => 'Rhododendron ferrugineux',
                'plant_scientific_name' => 'Rhododendron ferrugineum',
                'plant_description' => 'Arbuste à feuilles persistantes avec des grappes de fleurs rose vif. Typique des landes alpines.',
                'plant_image_src' => 'rhododendron_ferrugineux',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 22,
                'plant_common_name' => 'Saxifrage à feuilles en coin',
                'plant_scientific_name' => 'Saxifraga cuneifolia',
                'plant_description' => 'Petite plante formant des coussinets, avec des fleurs blanches étoilées. Pousse dans les fissures rocheuses.',
                'plant_image_src' => 'saxifrage_a_feuilles_en_coin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 23,
                'plant_common_name' => 'Thym serpolet',
                'plant_scientific_name' => 'Thymus serpyllum',
                'plant_description' => 'Plante aromatique rampante aux petites fleurs roses. Appréciée pour ses propriétés médicinales.',
                'plant_image_src' => 'thym_serpolet',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 24,
                'plant_common_name' => 'Véronique des Alpes',
                'plant_scientific_name' => 'Veronica alpina',
                'plant_description' => 'Petite plante aux fleurs bleues en grappes courtes. Adaptée aux pelouses alpines.',
                'plant_image_src' => 'veronique_des_alpes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 25,
                'plant_common_name' => 'Baldingère',
                'plant_scientific_name' => 'Phalaris arundinacea',
                'plant_description' => 'Graminée vivace des zones humides, la Baldingère forme de grandes touffes de tiges rigides et de longues feuilles rubanées. Ses inflorescences en épis sont de couleur vert pâle.',
                'plant_image_src' => 'baldingere',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 26,
                'plant_common_name' => 'Balsamine à petites fleurs',
                'plant_scientific_name' => 'Impatiens parviflora',
                'plant_description' => 'Petite plante annuelle aux fleurs discrètes, jaune pâle, la Balsamine à petites fleurs se développe rapidement en sous-bois ombragés. Ses feuilles sont ovales et dentées, et ses graines sont éjectées à maturité.',
                'plant_image_src' => 'balsamine_a_petites_fleurs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 27,
                'plant_common_name' => 'Balsamine de l\'Hymalaya',
                'plant_scientific_name' => 'Impatiens glandulifera',
                'plant_description' => 'Plante envahissante aux fleurs roses ou pourpres en forme de casque, la Balsamine de l\'Himalaya pousse souvent près des cours d\'eau. Ses longues tiges creuses et ses feuilles dentées la rendent reconnaissable.',
                'plant_image_src' => 'balsamine_de_l_hymalaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 28,
                'plant_common_name' => 'Balsamine des bois',
                'plant_scientific_name' => 'Impatiens noli-tangere',
                'plant_description' => 'Cette plante annuelle est reconnaissable à ses fleurs jaunes en forme de clochettes. Elle pousse dans les zones humides et ombragées, et ses feuilles sont dentées et pointues.',
                'plant_image_src' => 'balsamine_des_bois',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 29,
                'plant_common_name' => 'Bazzanie trinlobée',
                'plant_scientific_name' => 'Bazzania trilobata',
                'plant_description' => 'Cette mousse vivace se distingue par ses feuilles en forme de lobes trilobés qui forment des tapis denses dans les forêts humides. Elle est souvent de couleur vert sombre.',
                'plant_image_src' => 'bazzanie_trinlobee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 30,
                'plant_common_name' => 'Buis commun',
                'plant_scientific_name' => 'Buxus sempervirens',
                'plant_description' => 'Arbuste au feuillage persistant, le Buis commun est souvent utilisé pour les haies et l\'art topiaire. Ses petites feuilles vert foncé sont ovales et coriaces, et il produit de petites fleurs jaunes discrètes.',
                'plant_image_src' => 'buis_commun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 31,
                'plant_common_name' => 'Callitriche des eaux stagnantes',
                'plant_scientific_name' => 'Callitriche stagnalis',
                'plant_description' => 'Plante aquatique flottante, la Callitriche des eaux stagnantes a de petites feuilles rondes qui forment des rosettes à la surface de l\'eau. Ses tiges sont fines et ses fleurs sont très petites et discrètes.',
                'plant_image_src' => 'callitriche_des_eaux_stagnantes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 32,
                'plant_common_name' => 'Callitriche à crochets',
                'plant_scientific_name' => 'Callitriche hamulata',
                'plant_description' => 'Cette plante aquatique se caractérise par ses feuilles flottantes en forme de spatule et ses graines qui possèdent de petits crochets. Elle préfère les eaux calmes et peu profondes.',
                'plant_image_src' => 'callitriche_a_crochets',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 33,
                'plant_common_name' => 'Callune commune',
                'plant_scientific_name' => 'Calluna vulgaris',
                'plant_description' => 'Arbrisseau à feuilles persistantes, la Callune commune forme des tapis denses dans les landes. Ses petites fleurs roses ou violettes apparaissent à la fin de l\'été, et ses feuilles sont petites et écailleuses.',
                'plant_image_src' => 'callune_commune',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 34,
                'plant_common_name' => 'Campanule gantelée',
                'plant_scientific_name' => 'Campanula trachelium',
                'plant_description' => 'Cette campanule vivace est reconnaissable à ses fleurs en forme de clochettes bleues, qui sont poilues à l\'intérieur. Ses feuilles sont en forme de cœur et dentelées, et la plante peut atteindre jusqu\'à un mètre de hauteur.',
                'plant_image_src' => 'campanule_gantelee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 35,
                'plant_common_name' => 'Canche cespiteuse',
                'plant_scientific_name' => 'Deschampsia cespitosa',
                'plant_description' => 'Graminée vivace formant des touffes denses, la Canche cespiteuse produit des inflorescences plumeuses et légères qui changent de couleur, passant du vert au doré à la fin de l\'été.',
                'plant_image_src' => 'canche_cespiteuse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 36,
                'plant_common_name' => 'Canche fluxueuse',
                'plant_scientific_name' => 'Avenella flexuosa',
                'plant_description' => 'Cette petite graminée des landes et des sous-bois se distingue par ses tiges fines et flexibles, qui portent des inflorescences légères et éparses. Ses feuilles sont étroites et souvent recourbées.',
                'plant_image_src' => 'canche_fluxueuse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 37,
                'plant_common_name' => 'Capillaire des murailles',
                'plant_scientific_name' => 'Asplenium trichomanes',
                'plant_description' => 'Petite fougère gracieuse, la Capillaire des murailles pousse souvent sur les murs et les rocailles. Elle se distingue par ses frondes fines et légères, divisées en petites folioles rondes ou ovales.',
                'plant_image_src' => 'capillaire_des_murailles',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 38,
                'plant_common_name' => 'Cardamine amère',
                'plant_scientific_name' => 'Cardamine amara',
                'plant_description' => 'Plante vivace des zones humides, la Cardamine amère possède des fleurs blanches ou roses en petites grappes. Ses feuilles sont composées de folioles arrondies, et elle préfère les sols riches en eau.',
                'plant_image_src' => 'cardamine_amere',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 39,
                'plant_common_name' => 'Cardamine hérissée',
                'plant_scientific_name' => 'Cardamine hirsuta',
                'plant_description' => 'Plante annuelle à petites fleurs blanches, la Cardamine hérissée pousse dans les sols perturbés. Ses feuilles sont composées de plusieurs petites folioles arrondies, et ses siliques sont longues et fines.',
                'plant_image_src' => 'cardamine_herissee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 40,
                'plant_common_name' => 'Centaurée noire',
                'plant_scientific_name' => 'Centaurea nigra',
                'plant_description' => 'Cette plante vivace produit des capitules de fleurs pourpres ou roses, avec un centre noir. Ses feuilles sont allongées et légèrement poilues, et elle est souvent trouvée dans les prairies.',
                'plant_image_src' => 'centauree_noire',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 41,
                'plant_common_name' => 'Charme commun',
                'plant_scientific_name' => 'Carpinus betulus',
                'plant_description' => 'Arbre à feuillage caduc, le Charme commun a des feuilles dentelées et nervurées en forme de losange. Son écorce est grise et lisse, se fissurant avec l\'âge. Il forme souvent des haies denses.',
                'plant_image_src' => 'charme_commun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_id' => 42,
                'plant_common_name' => 'Châtaignier',
                'plant_scientific_name' => 'Castanea sativa',
                'plant_description' => 'Grand arbre avec une écorce fissurée et des feuilles allongées et dentelées, le Châtaignier produit des fruits comestibles (châtaignes) en automne, enfermés dans des bogues épineuses.',
                'plant_image_src' => 'chataignier',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}