<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlantsFamilyTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('plants_family')->insert([
            [
                'plant_family_id' => 1,
                'plants_family_name' => 'Asteraceae',
                'plant_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 2,
                'plants_family_name' => 'Asteraceae',
                'plant_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 3,
                'plants_family_name' => 'Adoxaceae',
                'plant_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 4,
                'plants_family_name' => 'Ericaceae',
                'plant_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 5,
                'plants_family_name' => 'Rosaceae',
                'plant_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 6,
                'plants_family_name' => 'Rosaceae',
                'plant_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 7,
                'plants_family_name' => 'Brassicaceae',
                'plant_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 8,
                'plants_family_name' => 'Apiaceae',
                'plant_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 9,
                'plants_family_name' => 'Rubiaceae',
                'plant_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 10,
                'plants_family_name' => 'Rosaceae',
                'plant_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 11,
                'plants_family_name' => 'Rosaceae',
                'plant_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 12,
                'plants_family_name' => 'Campanulaceae',
                'plant_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 13,
                'plants_family_name' => 'Asteraceae',
                'plant_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 14,
                'plants_family_name' => 'Onagraceae',
                'plant_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 15,
                'plants_family_name' => 'Gentianaceae',
                'plant_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 16,
                'plants_family_name' => 'Geraniaceae',
                'plant_id' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 17,
                'plants_family_name' => 'Liliaceae',
                'plant_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 18,
                'plants_family_name' => 'Pinaceae',
                'plant_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 19,
                'plants_family_name' => 'Orchidaceae',
                'plant_id' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 20,
                'plants_family_name' => 'Asteraceae',
                'plant_id' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 21,
                'plants_family_name' => 'Ericaceae',
                'plant_id' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 22,
                'plants_family_name' => 'Saxifragaceae',
                'plant_id' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 23,
                'plants_family_name' => 'Lamiaceae',
                'plant_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 24,
                'plants_family_name' => 'Plantaginaceae',
                'plant_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 25,
                'plants_family_name' => 'Poaceae',
                'plant_id' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 26,
                'plants_family_name' => 'Balsaminaceae',
                'plant_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 27,
                'plants_family_name' => 'Balsaminaceae',
                'plant_id' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 28,
                'plants_family_name' => 'Balsaminaceae',
                'plant_id' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 29,
                'plants_family_name' => 'Lepidoziaceae',
                'plant_id' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 30,
                'plants_family_name' => 'Buxaceae',
                'plant_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 31,
                'plants_family_name' => 'Plantaginaceae',
                'plant_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 32,
                'plants_family_name' => 'Plantaginaceae',
                'plant_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 33,
                'plants_family_name' => 'Ericaceae',
                'plant_id' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 34,
                'plants_family_name' => 'Campanulaceae',
                'plant_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 35,
                'plants_family_name' => 'Poaceae',
                'plant_id' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 36,
                'plants_family_name' => 'Poaceae',
                'plant_id' => 36,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 37,
                'plants_family_name' => 'Aspleniaceae',
                'plant_id' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 38,
                'plants_family_name' => 'Brassicaceae',
                'plant_id' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 39,
                'plants_family_name' => 'Brassicaceae',
                'plant_id' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 40,
                'plants_family_name' => 'Asteraceae',
                'plant_id' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 41,
                'plants_family_name' => 'Betulaceae',
                'plant_id' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plant_family_id' => 42,
                'plants_family_name' => 'Fagaceae',
                'plant_id' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}